package com.yunfang.rest.LoginProject.mybatis.model.eBillModel;

public class AnliData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.ID
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AZS_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer azsChengjiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AZZ_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer azzChengjiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer azsGuapai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer azzGuapai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AFZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer afzsGuapai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.AFZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer afzzGuapai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anli_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    private Integer citycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.ID
     *
     * @return the value of anli_data.ID
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.ID
     *
     * @param id the value for anli_data.ID
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AZS_CHENGJIAO
     *
     * @return the value of anli_data.AZS_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAzsChengjiao() {
        return azsChengjiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AZS_CHENGJIAO
     *
     * @param azsChengjiao the value for anli_data.AZS_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAzsChengjiao(Integer azsChengjiao) {
        this.azsChengjiao = azsChengjiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AZZ_CHENGJIAO
     *
     * @return the value of anli_data.AZZ_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAzzChengjiao() {
        return azzChengjiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AZZ_CHENGJIAO
     *
     * @param azzChengjiao the value for anli_data.AZZ_CHENGJIAO
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAzzChengjiao(Integer azzChengjiao) {
        this.azzChengjiao = azzChengjiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AZS_GUAPAI
     *
     * @return the value of anli_data.AZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAzsGuapai() {
        return azsGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AZS_GUAPAI
     *
     * @param azsGuapai the value for anli_data.AZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAzsGuapai(Integer azsGuapai) {
        this.azsGuapai = azsGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AZZ_GUAPAI
     *
     * @return the value of anli_data.AZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAzzGuapai() {
        return azzGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AZZ_GUAPAI
     *
     * @param azzGuapai the value for anli_data.AZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAzzGuapai(Integer azzGuapai) {
        this.azzGuapai = azzGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AFZS_GUAPAI
     *
     * @return the value of anli_data.AFZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAfzsGuapai() {
        return afzsGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AFZS_GUAPAI
     *
     * @param afzsGuapai the value for anli_data.AFZS_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAfzsGuapai(Integer afzsGuapai) {
        this.afzsGuapai = afzsGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.AFZZ_GUAPAI
     *
     * @return the value of anli_data.AFZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getAfzzGuapai() {
        return afzzGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.AFZZ_GUAPAI
     *
     * @param afzzGuapai the value for anli_data.AFZZ_GUAPAI
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setAfzzGuapai(Integer afzzGuapai) {
        this.afzzGuapai = afzzGuapai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anli_data.CITYCODE
     *
     * @return the value of anli_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anli_data.CITYCODE
     *
     * @param citycode the value for anli_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }
}