package com.yunfang.rest.LoginProject.mybatis.model.eBillModel;

public class BasicData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.ID
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.J_ZHOUBIANPEITAO
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private Integer jZhoubianpeitao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.J_XIAOQUPINGJI
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private Integer jXiaoqupingji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.J_JICHUSHULIANG
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private Integer jJichushuliang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.J_ZHISHU
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private Integer jZhishu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basic_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    private Integer citycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.ID
     *
     * @return the value of basic_data.ID
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.ID
     *
     * @param id the value for basic_data.ID
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.J_ZHOUBIANPEITAO
     *
     * @return the value of basic_data.J_ZHOUBIANPEITAO
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public Integer getjZhoubianpeitao() {
        return jZhoubianpeitao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.J_ZHOUBIANPEITAO
     *
     * @param jZhoubianpeitao the value for basic_data.J_ZHOUBIANPEITAO
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setjZhoubianpeitao(Integer jZhoubianpeitao) {
        this.jZhoubianpeitao = jZhoubianpeitao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.J_XIAOQUPINGJI
     *
     * @return the value of basic_data.J_XIAOQUPINGJI
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public Integer getjXiaoqupingji() {
        return jXiaoqupingji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.J_XIAOQUPINGJI
     *
     * @param jXiaoqupingji the value for basic_data.J_XIAOQUPINGJI
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setjXiaoqupingji(Integer jXiaoqupingji) {
        this.jXiaoqupingji = jXiaoqupingji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.J_JICHUSHULIANG
     *
     * @return the value of basic_data.J_JICHUSHULIANG
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public Integer getjJichushuliang() {
        return jJichushuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.J_JICHUSHULIANG
     *
     * @param jJichushuliang the value for basic_data.J_JICHUSHULIANG
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setjJichushuliang(Integer jJichushuliang) {
        this.jJichushuliang = jJichushuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.J_ZHISHU
     *
     * @return the value of basic_data.J_ZHISHU
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public Integer getjZhishu() {
        return jZhishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.J_ZHISHU
     *
     * @param jZhishu the value for basic_data.J_ZHISHU
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setjZhishu(Integer jZhishu) {
        this.jZhishu = jZhishu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basic_data.CITYCODE
     *
     * @return the value of basic_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basic_data.CITYCODE
     *
     * @param citycode the value for basic_data.CITYCODE
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }
}