package com.yunfang.rest.LoginProject.mybatis.dao.eBillDao;

import com.yunfang.rest.LoginProject.mybatis.model.eBillModel.AnliData;

public interface AnliDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anli_data
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    int insert(AnliData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anli_data
     *
     * @mbg.generated Tue Mar 06 15:55:57 CST 2018
     */
    int insertSelective(AnliData record);
}