package com.yunfang.rest.LoginProject.mybatis.dao.eBillDao;

import com.yunfang.rest.LoginProject.mybatis.model.eBillModel.BasicData;

public interface BasicDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    int insert(BasicData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_data
     *
     * @mbg.generated Tue Mar 06 15:57:42 CST 2018
     */
    int insertSelective(BasicData record);
}